### ISSUE TITLE
Application Insight - Not Optional

### ISSUE THREAD

**Issue by AndreeaDan27** [microsoft/Power-CAT-Copilot-Studio-Kit#29]
Hi!

The documentation states Application Insights to be optional. However, I cannot create the solution without the Application Insights connection. 

![image](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/assets/120377092/5bb5db53-c895-4d54-9b16-5d4fdddac079)

I can however after creating the connection

![image](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/assets/120377092/4155ff1e-bf74-4756-9060-41efec7b8f6b)

**Comment by HenryJammes** [comment]
Thanks @AndreeaDan27.
That's a great point.
We're thinking of indeed of making that optional, or at least being configurable differently so it's not a required step when deploying the solution

**Comment by HenryJammes** [comment]
Created PR #30 to fix this while we remove this in the next version.
Cc. @patilravikiran

**Comment by patilravikiran** [comment]
Fixed this issue in Dev. Will be available in next release.
