### ISSUE TITLE
Once you will enable channel security to Yes , there is no option to go back as Environement variable will still be mandate 

### ISSUE THREAD

**Issue by gautam990** [microsoft/Power-CAT-Copilot-Studio-Kit#31]
Once you will enable channel security to Yes , there is no option to 
![image](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/assets/34851523/ed609f26-1dc1-41dc-8677-c664fdf7415a)
go back as Environement variable will still be mandate .

**Comment by patilravikiran** [comment]
Fixed this issue in Dev. Will be available in next release.

**Comment by patilravikiran** [comment]
@gautam990, Fixed issue. Please get latest solution.
