### ISSUE TITLE
Incase Web channel security is disabled and Authentication is set manually , how to setup the connection

### ISSUE THREAD

**Issue by gautam990** [microsoft/Power-CAT-Copilot-Studio-Kit#32]
Incase Web channel security is disabled and Authentication is set manually , how to setup the connection

![image](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/assets/34851523/9b256b95-21bc-42e9-9c0b-c3f833805522)

Web channel security 
![image](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/assets/34851523/bf29e745-7ca4-448a-9545-22ddb0883bd2)

It still keep asking me to login in response and no reply

**Comment by HenryJammes** [comment]
Hi @gautam990 --
Good call - today this isn't possible, the kit only works for unauthenticated bots.
Let me document these limitations more clearly while we address those in a future release.

**Comment by patilravikiran** [comment]
@gautam990, we are adding new feature in coming release as part of which we will be able to test manually authenticated bots with Entra ID V2. We have completed development, will be available in next release.
