### ISSUE TITLE
Error while running test case. 

### ISSUE THREAD

**Issue by kaul-vineet** [microsoft/Power-CAT-Copilot-Studio-Kit#36]
## Error while running test case. 

The flow **Run Copilot Tests** fails with error for test type **Response Match**: 

_ _ Action 'Create_Copilot_Test_Result' failed: Unable to process template language expressions in action 'Create_Copilot_Test_Result' inputs at line '0' and column '0': 'The template language expression 'if( empty(body('Filter_array:_Messages_from_Bot')), 4, if( equals(items('Apply_to_each_Copilot_Test')?['cat_testtypecode'], 3), if( equals( json(string(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['attachments'])), json(string(items('Apply_to_each_Copilot_Test')?['cat_expectedattachmentsjson'])) ), 1, 2 ), if( not(empty(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'])), if( or( contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'ContentError'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'DataLossPreventionViolation'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'FlowActionException'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'FlowActionBadRequest'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'FlowActionTimedOut'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'InvalidContent'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'InfiniteLoopInBotContent'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'LatestPublishedVersionNotFound'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'RedirectToDisabledDialog'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'RedirectToNonExistentDialog'), contains(body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'], 'SystemError') ), 4, if( equals(items('Apply_to_each_Copilot_Test')?['cat_testtypecode'], 1), if( equals( items('Apply_to_each_Copilot_Test')?['cat_expectedresponse'], body('Filter_array:_Messages_from_Bot')[outputs('Message_Position')]?['text'] ), 1, 2 ), if( equals(items('Apply_to_each_Copilot_Test')?['cat_testtypecode'], 2), if( equals(body('Get_Copilot_Configuration')?['cat_isenrichedwithconversationtranscripts'], true), 5, 3 ), if( equals(items('Apply_to_each_Copilot_Test')?['cat_testtypecode'], 4), if( or( equals(items('Apply_to_each_Copilot_Test')?['cat_generativeansweroutcomecode'], 1), equals(items('Apply_to_each_Copilot_Test')?['cat_generativeansweroutcomecode'], 2) ), if( equals(body('Get_Copilot_Configuration')?['cat_isgeneratedanswersanalysisenabled'], true), 5, 3 ), if( or( equals(items('Apply_to_each_Copilot_Test')?['cat_generativeansweroutcomecode'], 3), equals(items('Apply_to_each_Copilot_Test')?['cat_generativeansweroutcomecode'], 4) ), if( equals(body('Get_Copilot_Configuration')?['cat_isazureapplicationinsightsenabled'], true), 5, 3 ), 3 ) ), 5 ) ) ) ), 3 ) ) ) ' cannot be evaluated because array index '1' is outside bounds (0, 0) of array. Please see https://aka.ms/logicexpressions for usage details.'. _ _

The error occurs in the **Apply to each Copilot Test** loop at the Dataverse operation control in the flow. The input to the flow is 

_ _[
  {
    "@odata.type": "#Microsoft.Dynamics.CRM.cat_copilottest",
    "@odata.id": "https://orgf8380473.crm.dynamics.com/api/data/v9.1/cat_copilottests(30d6495d-1b5b-ef11-a317-000d3a1a1139)",
    "@odata.etag": "W/\"11571322\"",
    "@odata.editLink": "cat_copilottests(30d6495d-1b5b-ef11-a317-000d3a1a1139)",
    "cat_testutterance": "I want emergency assistance for flood.",
    "cat_copilottestid@odata.type": "#Guid",
    "cat_copilottestid": "30d6495d-1b5b-ef11-a317-000d3a1a1139",
    "cat_expectedresponse": "Hello world",
    "cat_secondsbeforegettinganswer@OData.Community.Display.V1.FormattedValue": "5",
    "cat_secondsbeforegettinganswer": 5,
    "cat_testtypecode@OData.Community.Display.V1.FormattedValue": "Response Match",
    "cat_testtypecode": 1,
    "cat_isstartconversationeventsent@OData.Community.Display.V1.FormattedValue": "Yes",
    "cat_isstartconversationeventsent": true,
    "cat_name": "Natural Disaster"
  }
]_ _

**Comment by gulzarudheen** [comment]
@kaul-vineet The failure was caused by the absence of initial bot response when the start event was active, leading to an array position mismatch during position calculation. The expression has been updated to handle this scenario, and the bug is now resolved.
