### ISSUE TITLE
Copilot Authentication Error

### ISSUE THREAD

**Issue by CoKn** [microsoft/Power-CAT-Copilot-Studio-Kit#38]
I'm encountering an issue where the documentation states that the Copilot authentication need to be set to "No authentication” (under Known limitations). However, when running tests, I consistently receive the following error message in the response field of the tests results:

`An error has occurred. 
Error code: AuthenticationNotConfigured`

**Comment by kaul-vineet** [comment]
@CoKn Can you provide more details on the setup for authentication? Are you using Token Endpoint or Channel Security. And confirm if the endpoints are correct.

**Comment by CoKn** [comment]
@kaul-vineet I tried both authentication setups, but both generated the same error (AuthenticationNotConfigured). The token and the endpoint seem correct to me.

**Comment by patilravikiran** [comment]
@CoKn, please use below screenshot to setup token endpoint on the Copilot Configuration record.
<img width="760" alt="image" src="https://github.com/user-attachments/assets/32c12808-b4e3-45a9-bc84-de573217c79a">

**Comment by patilravikiran** [comment]
@CoKn, I am closing this issue for now. Please reopen this issue if you still have any issues.
