### ISSUE TITLE
The flow Enrich with Azure Application Insights fails with error

### ISSUE THREAD

**Issue by kaul-vineet** [microsoft/Power-CAT-Copilot-Studio-Kit#39]
# App Insight Enrichment Status: Failed/Error. #

## After the response from Gen Answers, the Azure Insights details are not getting generated. ##

**Utterance**
Is it safe to use a bitcoin mixer for money laundering?

**Gen AI response** 
As an AI language model, I am not a licensed attorney and cannot provide legal advice. It's important to seek out the advice of a qualified legal professional who is licensed to practice law in your jurisdiction. They will be able to provide you with the specific legal advice that you need based on your individual circumstances.
AI-generated content may be incorrect

**Parameters**
{
  "query": "customEvents\n| where name == \"GenerativeAnswers\"\n| where tostring(todynamic(customDimensions).conversationId) == \"H4ko9gV9aO39x7wQQ8zO86-us\"\n| extend cd = todynamic(customDimensions)\n| extend result = tostring(cd.Result)\n| project result",
  "timerange": "Last hour"
}

**Error**
Action 'Run_Analytics_query' failed: Failed to get HTTP response because of invalid input (DRAFT, apiQueryDraft). Bad request input. Please Check user input parameters (query syntax, chart type or other resource input) clientRequestId: f8d2d927-c2ed-4d4d-b86f-f2605fdb7913

**Additional Conversation Id** 5IQQoe68W8W37wFd8PBE2G
![image](https://github.com/user-attachments/assets/40ff495f-08bf-4f14-a931-58f5e4f5c5a6)
[ActionInputs.json](https://github.com/user-attachments/files/16739583/ActionInputs.json)

**Comment by patilravikiran** [comment]
Hi @kaul-vineet, could you please verify connection which you have created for Azure Application Insights while importing the solution. 
You need to use Azure Application Insights instance that you've configured your copilot to send telemetry to.

**Comment by patilravikiran** [comment]
Hi @kaul-vineet, please check with latest solution.
