### ISSUE TITLE
Feedback: Specify measure metrics for time delay in Copilot configuration.

### ISSUE THREAD

**Issue by kaul-vineet** [microsoft/Power-CAT-Copilot-Studio-Kit#40]
# Measurement metric indicator #

**Good to have minutes/second indicator for correct delay input**

**Delay for Azure Application Insights Enrichment**
**Delay for Conversation Transcripts Enrichment**

![image](https://github.com/user-attachments/assets/3e7d801e-f504-4d26-bec6-a4705cbcd0d7)

**Comment by patilravikiran** [comment]
Hi @kaul-vineet, we have already added indicators for minutes/seconds within fields description. Are you suggesting having same within field labels?

**Comment by kaul-vineet** [comment]
I don't see them when I am creating Copilot definition.

**Comment by patilravikiran** [comment]
Hi @kaul-vineet, Thanks for raising this. We are going to remove these fields completely from UI and handle this logic at backend. The fix will be available in the upcoming release.

**Comment by patilravikiran** [comment]
Fixed this issue in Dev. Will be available in next release.

**Comment by patilravikiran** [comment]
@kaul-vineet, we have moved these changes. Please use latest solution.
