### ISSUE TITLE
Importing solution can be blocked by dlp policy

### ISSUE THREAD

**Issue by jltnf54** [microsoft/Power-CAT-Copilot-Studio-Kit#41]
Some components do lookups on dataverse by organization and can be blocked by dlp policies.  Is this needed?  Can the solution just run in the same organization instance?

**Comment by patilravikiran** [comment]
@jltnf54, Thanks for raising this. Are you saying Power Automate actions to retrieve data from selected environment?

**Comment by jltnf54** [comment]
Yeah when you use the dataverse actions in the power automate using list by selected environment, or anything call to dataverse using selected environment.  It is blocked, is there a possibility to just use the default environment to avoid cross environment lookups

**Comment by psimolin** [comment]
This is required for cross-environment Copilot Studio Bot testing in Copilot Studio Kit. We will consider releasing unmanaged version of the Kit to allow custom modifications based on specific requirements such as this.
