### ISSUE TITLE
How can you export all configuration and test data?

### ISSUE THREAD

**Issue by joewelds** [microsoft/Power-CAT-Copilot-Studio-Kit#50]
I exported the powerCAT test kit solution as I was hoping to back up the entirety of my work in the tool thus far. I looked in the downloaded export and did not find any of my configuration/data for the copilots, insights, or Dataverse. Is there an easy way to export that instance data for backup or migration purposes?

**Comment by psimolin** [comment]
You could leverage the export to Excel functionality in the Copilot Studio Kit (standard platform feature).

https://learn.microsoft.com/en-us/power-apps/user/export-excel-static-worksheet

Please let us know if you are looking for something else/more.

**Comment by joewelds** [comment]
The way I tried it doesn't seem to work. All the configuration elements are not available to be displayed in the table. It seems to export only the displayed columns. Note that none of the app insights config data is available to be displayed/exported. Is this the way to export you suggested or am I looking in the wrong place? 
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/09c12afb-0d8c-43d5-8823-cbdfb3aa7cc7">

I did see what looks like an option in the Data tab
<img width="345" alt="image" src="https://github.com/user-attachments/assets/abfbd479-7483-475c-915b-1b89e486bdd8">
When I open each of those tables I can export and get a zip of a csv that appears to contain all rows/columns. 
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/f0ecf155-6297-449e-9d37-f049904d08f2">
What I downloaded:
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/c3be3445-d412-42ef-b77b-a4cca21ed9e4">

Can you confirm those are the correct tables that I can use to restore my copilot studio test kit fully from exports?

**Comment by psimolin** [comment]
Export through Data tab should work in your case. "Copilot Configuration" or "Agent Configuration", as it is called in the latest release has all the configuration data in it, including App Insights and Dataverse related settings.
