### ISSUE TITLE
Importing tests causes error in ui control

### ISSUE THREAD

**Issue by joewelds** [microsoft/Power-CAT-Copilot-Studio-Kit#57]
Description: 
When importing tests from CSV, the Allow Duplicates control is replaced with "Error loading control" link.

Steps to reproduce: 
1 - Click Tests tab in left navigation of copilot test kit
2 - Open Import From Excel down arrow in the top menu
3 - Click Import From CSV
4 - Select your CSV file
5 - Click Next in the slide out panel

Expected Behavior: 
All controls load as expected

Actual Behavior:
Error loading control link shown where toggle UI component should be. 

Note this was run on MacOS.
Microsoft Edge for Business
[Learn more about Microsoft Edge for Business](https://go.microsoft.com/fwlink/?linkid=2244048)
Version 129.0.2792.65 (Official build) (arm64)

[ErrorDetails.txt](https://github.com/user-attachments/files/17281061/ErrorDetails.txt)
<img width="753" alt="chrome_rKMwRABW5r" src="https://github.com/user-attachments/assets/d4150bf6-4cca-4b2b-8cf7-9e447389151b">
<img width="321" alt="chrome_Bwjo1vkJ66" src="https://github.com/user-attachments/assets/f2b67bea-7ee5-45a5-838d-a7816b6b5044">
<img width="322" alt="chrome_YyTkBEEeV7" src="https://github.com/user-attachments/assets/58f35043-dad2-4c63-84a9-0ebf25bcee23">

**Comment by patilravikiran** [comment]
Acknowledged.

**Comment by patilravikiran** [comment]
Hi @joewelds , we don't see this issue at our end. Please clear browser cookies and caches and give a try. If issue still persists, please raise a support ticket. This issue is not specific to Copilot Studio Kit.

![Image](https://github.com/user-attachments/assets/1e5efcf0-2fe7-4c3f-9ec6-cd3bfc7bfda1)
