### ISSUE TITLE
Getting error while running test cases "Error code: IntegratedAuthenticationNotSupportedInChannel"

### ISSUE THREAD

**Issue by bhupenbiwal** [microsoft/Power-CAT-Copilot-Studio-Kit#59]
Hi folks,

Hope you are well.

We need a help one below issue which we are facing while running test cases.

Below are the key points which we have used while configuring the copilot in studio kit.
1. We have disabled 'Web Channel" security.
2. We are using token endpoint of Mobile app channel from copilot.

Error details "Sorry, something unexpected happened. We’re looking into it. Error code: IntegratedAuthenticationNotSupportedInChannel".

Please suggest if what we are missing here in copilot studio kit or copilot.

Thanks for your help in advance.

Bhupender Kumar

**Comment by patilravikiran** [comment]
Acknowledged.

**Comment by psimolin** [comment]
@bhupenbiwal  could you confirm the authentication settings you are using? (unauthenticated, authenticate with microsoft, authenticate manually (entra, oauth, entra with sso, etc).

**Comment by bhupenbiwal** [comment]
We are using 'No Authentication' on copilot side. For your ref: please find the snapshot of settings.

![Image](https://github.com/user-attachments/assets/2e1d7850-86f6-4cd5-ab3d-addef133d482)

**Comment by patilravikiran** [comment]
@bhupenbiwal, 
Thanks for your response. We ran couple of tests at our end, its working fine. Can you also share a screenshot for Web Channel Security section? We would also like you to publish your bot one more time and then give a try.

**Comment by bhupenbiwal** [comment]
Thanks for the response @patilravikiran.

Here is the snapshot of Web channel security:
![Image](https://github.com/user-attachments/assets/17b7af5f-01e5-4c29-924d-8b3692641fb6)

Also, We had published copilot multiple times. Still, we are getting the same error.

**Comment by psimolin** [comment]
Thanks for the additional information @bhupenbiwal

We don't see anything obvious wrong with these settings.

Could you confirm the following:
1) The Copilot has been published after setting the "Authentication" to "No authentication"
2) Please open the demo site for this Copilot and confirm if you are able to converse with the Copilot (three dots -> "Go to demo website")

**Comment by patilravikiran** [comment]
@bhupenbiwal ,
Gentle reminder. Please provide an update. If you are still facing an issue after following above steps, please create another sample bot and perform testing again.

**Comment by patilravikiran** [comment]
@bhupenbiwal ,
Gentle reminder to provide an update.

**Comment by patilravikiran** [comment]
Closing this issue as no response from user.
