### ISSUE TITLE
Error using Application Insights - Could not load file or assembly

### ISSUE THREAD

**Issue by kenowak** [microsoft/Power-CAT-Copilot-Studio-Kit#60]
This is my fist time using Copilot Kit and I'm not sure I have the Application Insight setup correctly, I get this error when running the tests. Is there something additional needed in my Environment to load the assembly?

Action 'Generate_Azure_App_Insights_Access_Token' failed: An error occurred in cat_GenerateAppInsightsAccessToken: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.16.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'Microsoft.Identity.Client, Version=4.16.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' at POWERCAT.Plugins.ApplicationInsightsApi.InvokeApplicationInsightsApi.GenerateAppInsightsAccessTokenAsync(String tenantId, String clientId, String clientSecret) at POWERCAT.Plugins.ApplicationInsightsApi.InvokeApplicationInsightsApi.InvokeAppInsightsApiUsingMessage(IPluginExecutionContext context, ITracingService tracingService) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by patilravikiran** [comment]
Acknowledged.

**Comment by patilravikiran** [comment]
Hi @kenowak, I assume you are using unmanaged version of CopilotStudioAccelerator by just updating few properties. Can you please download latest managed solution from [Latest releases](https://github.com/microsoft/Power-CAT-Copilot-Studio-Kit/releases/tag/CopilotStudioAccelerator-September2024) and try again?

**Comment by kenowak** [comment]
Hi @patilravikiran, I'm using the latest managed version.

**Comment by patilravikiran** [comment]
Hi @kenowak, please share the solution so we can import and see if it can be replicated at our end.

**Comment by patilravikiran** [comment]
@kenowak , Gentle reminder to share the solution.

**Comment by kenowak** [comment]
@patilravikiran  here you go

[CopilotStudioAccelerator_20240918.1_managed.zip](https://github.com/user-attachments/files/17381907/CopilotStudioAccelerator_20240918.1_managed.zip)

**Comment by patilravikiran** [comment]
@kenowak , Thanks, it helped me to reproduce and resolve this issue. The fix will be available in next release. 
Proposed date for next release - 1st week of November.

**Comment by kenowak** [comment]
Thanks @patilravikiran !

**Comment by carlitos-espinoza** [comment]
Hi, is there any update on when this fix will be released?
Thanks.

**Comment by psimolin** [comment]
Hello @carlitos-espinoza 

Plan is to do the next release within a week.

Thank you

**Comment by patilravikiran** [comment]
Closing as this issue is resolved. Please import solution from latest release and let us know if you are still facing this issue.
