### ISSUE TITLE
Adaptive Card Validation Not Working

### ISSUE THREAD

**Issue by faizmodisweng** [microsoft/Power-CAT-Copilot-Studio-Kit#65]
Scenario : Trying to validate Adaptive Card using Attachment type of Test

Actual Behavior : Getting result as "Error" each time, as always getting "No response" as Bot response.

Expected Behavior : The kit should be able to get the actual response which would be used to validate against the expected response provided.

Please let me know if any further information is required, thank you.

**Comment by psimolin** [comment]
Are you getting the correct response from the bot if you test from within the copilot studio or demo site? Are you getting any responses from the bot when testing with the kit (e.g. just any response match test). Have you published the bot after making the changes?

**Comment by faizmodisweng** [comment]
1. I am getting the correct response from bot from copilot studio and from demo site.

2. With response match and topic match also I am getting proper response when testing with the kit.

3. I have published the bot after making the changes.

To understand the behavior further, I had also tried by sending a message (as bot response) before the adaptive card, so that message was getting captured in the expected response while testing using the kit.

But when I am trying to return adaptive card directly as response to the utterances, I am getting results in the bot but not in the kit.

Please do let me know if any further information is required from my end.

Thank You.

**Comment by patilravikiran** [comment]
@faizmodisweng, thanks for raising this issue. Please confirm on below points.
1. As a result of your test run of attachment type, are you getting multiple messages from bot? It can happen that before adaptive card, bot might be sending additional messages.
2. Are you able to see anything in the Attachment field of Result record? If data is not sensitive, then I would request you to share screen shot of test and result record.

**Comment by patilravikiran** [comment]
@faizmodisweng , Gentle reminder to update.

**Comment by patilravikiran** [comment]
@faizmodisweng, Gentle reminder to update.

**Comment by patilravikiran** [comment]
Closing this issue as no response from user. Thanks.
